version: "3.9"  # optional since v1.27.0
services:
  fastapi:
    build: .
    image: philbell/niki.ie
    ports:
      - "80:80"
    volumes:
      - .:/code
    links:
      - qbittorrent
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload

  qbittorrent:
    image: linuxserver/qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - ~/Movies/tv:/tv
      - ~/Movies/films:/movies
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
    links:
      - plex

  plex:
      image: linuxserver/plex
      container_name: plex
      network_mode: host
      environment:
        - PUID=1000
        - PGID=1000
        - VERSION=docker
        - PLEX_CLAIM= #optional
      volumes:
        - ~/Movies/tv:/tv
        - ~/Movies/films:/movies
      restart: unless-stopped
